auto: true

#markdown: kramdown
highlighter: rouge
opaginate: 8
permalink: /:categories/:year-:i_month-:i_day/:title

title: Not a Cauchy Surface 
url: http:/hslynn.space
feed: /atom.xml
author_info: <a href="http://hslynn.github.io/">Hslynn</a>
